### ISSUE TITLE
Article preview

### ISSUE THREAD

**Issue by djansson** [victorjonsson/Arlima#21]
Hi,

I updated the plugin last night.

When i preview the articles in my lists, they don't have any style. Looked through the pages code (using Chrome) and my Arlima.css-file is linked from my theme into the admin page, but the page and the css doesn't cooperate...

In my Arlima-css-file in my WP-theme i have wrote a #arlima-preview .tmpl-X for each list, and it worked with the older plugin, but doesn't work now.

**Comment by victorjonsson** [comment]
Closing this... let me know if it still seems to be a problem
