### ISSUE TITLE
Teaser title not updating in preview with WordPress 4.0.

### ISSUE THREAD

**Issue by chredd** [victorjonsson/Arlima#52]
In WP 4.0beta4 the title of the teaser doesn't seem to update in preview mode (ctrl+p) from Arlima admin. No errors in console. Any JS library that might need an update?

Last tested with this commit of Arlima (3.0 beta43): https://github.com/victorjonsson/Arlima/commit/58731ccf5d7b71b5dc0f26fbcb2c11b1b14e756c

**Comment by victorjonsson** [comment]
This should now work... Open the issue again if the problem persists
