### ISSUE TITLE
Preview of unchanged list

### ISSUE THREAD

**Issue by drawski** [victorjonsson/Arlima#53]
When I click on "Preview list" or the eye button while managing lists, a popup window appears with a URL parameter `arlima-preview=yes`, and no teasers are rendering.
Of course when I change something on the list and then click on "Preview list" button, `arlima-preview` parameter is set to an integer number (e.g. 7) and whole list is rendered correctly.

Maybe the latest version of the list should be displayed in case of `arlima-preview=yes`?

**Comment by victorjonsson** [comment]
Let me know if this still seems to be an issue. I have changed the argument to `_` when viewing a list that is in a default state
