### ISSUE TITLE
Related posts

### ISSUE THREAD

**Issue by carlgrundberg** [victorjonsson/Arlima#68]
Hi,

I tried to get the connection between Related Posts for Wordpress and Arlima to work, and according to the documentation it should without any code. However i cant find that the function arlima_related_posts is used anywhere in the current release (beta) and I had to glue it together with something like this, is that the intended way, or is something broken?

``` php
// Show related post
function my_article_relations_hook( $data ) {
  if( $data['post'] )  {
    $data['content'] = arlima_related_posts($data['post']->ID);
  }
  return $data;
}
```

**Comment by victorjonsson** [comment]
The integration with MRP is now removed from the plugin. Here you can read how you could implement it yourself https://github.com/victorjonsson/Arlima/wiki/Integrate-%22Microkid%C2%B4s-Related-Posts%22-with-Arlima
