### ISSUE TITLE
New Streamer - Pre

### ISSUE THREAD

**Issue by ErikXXon** [victorjonsson/Arlima#78]
How do you use the "new" streamer_pre? 

Templates, Filters?

**Comment by victorjonsson** [comment]
After that you have enabled the streamer pre-text (wp-admin -> Manage Lists -> Settings) you will get two text inputs when you activate the streamer on an article. You access the pre-text using the variable `{{options.streamerPre}}`. The code in your article template might look something like:

```html
{{#options.streamerPre}}
   <div class="streamer divided">
       <div class="alignleft">{{{options.streamerPre}}}</div>
       <div class="alignright">{{{options.streamerContent}}}</div>
   </div>
{{/options.streamerPre}}
{{^options.streamerPre}}
   {{#html_streamer}}
      <div class="streamer"> {{{html_streamer}}} </div>
   {{/html_streamer}}
{{/options.streamerPre}}
```

**Comment by ErikXXon** [comment]
Thanks Victor! :)

**Comment by ErikXXon** [comment]
When fill in the extra pre field, my custom streamer dont work.

![streamer-pre](https://cloud.githubusercontent.com/assets/6995808/5687747/4de5b3d6-9850-11e4-83e1-a2a0769aa5ef.png)

When i don fill anything into the pre-field everything works.

![streamer-wo-pre](https://cloud.githubusercontent.com/assets/6995808/5687780/a22856a6-9850-11e4-9538-020f66cb4e35.png)

**Comment by victorjonsson** [comment]
The wrapper needs automatic overflow

```css
.streamer.divided {
   overflow: auto;
}
```
