### ISSUE TITLE
Broken JavaScript flow in admin panel when there's no format registered

### ISSUE THREAD

**Issue by drawski** [victorjonsson/Arlima#82]
Unregistering all default article formats using `arlima_unregister_format()` PHP function results with following JavaScript error (on `wp-admin/admin.php?page=arlima-main` page):
![2015-01-14_1541](https://cloud.githubusercontent.com/assets/3234828/5741950/dc7f3fec-9c0e-11e4-81fe-e0a7582e257f.png)

Maybe it should be checked in `ArlimaArticleForm.init()` whether `$formatSelect` variable is not empty before executing `ArlimaArticleSettingsMenu.addSelect()`?

Following fix in `ArlimaArticleForm.js` works fine for me:
```
if ($formatSelect.length > 0) {
    ArlimaArticleSettingsMenu.addSelect($formatSelect);
}
```

**Comment by drawski** [comment]
The fix was merged into master: https://github.com/victorjonsson/Arlima/pull/83
Maybe we could close the issue then?

**Comment by victorjonsson** [comment]
yes, sir!
