### ISSUE TITLE
Total social share

### ISSUE THREAD

**Issue by pre65** [victorjonsson/Arlima#86]
Is it possible to show total shares instead of comment count?

I use a nice little plugin that shows on posts the total number of shares and wonder if it is possible to show the total shares in Arlima?

Regards

Patric

**Comment by victorjonsson** [comment]
What plugin are we talking about?

**Comment by pre65** [comment]
kk-social-share-starter or Jetpacks share Victor.

Patric

**Comment by victorjonsson** [comment]
This requires that you write code... You probably want to use the filter  [arlima_article_end](https://github.com/victorjonsson/Arlima/wiki/Filters-and-actions#-arlima_article_end) 

Exactly how to implement it is not really a question about Arlima, it's a more suited question for the authors of the plugins you mention.

**Comment by pre65** [comment]
Thank´s for pointing out wich filter Victor. A little bit closer with my mission!

Patric
