### ISSUE TITLE
Add support for having the title size slider active without the html_title field

### ISSUE THREAD

**Issue by awikell** [victorjonsson/Arlima#87]
I have a use case where I don't want to use the ```{{html_title}}``` in my template since this always results in the title being wrapped in an ```<a>``` tag. This prevents me from wrapping any of the title's parent elements in an ```<a>``` tag itself since nested link elements are forbidden.

I can circumvent this using ```{{title}}```  but then the slider for the size of the title is disabled in the list manager, even if my template file also includes ```{{size}}```. I therefor propose that line 157 in ArlimaTemplateLoader.js:
```
supports['title'] = templateContent.indexOf('{{html_title}}') > -1;
```
is altered to work similarly to the previous line (156) which checks for editor support:
```
supports['title'] = templateContent.indexOf('{{html_title}}') > -1 || templateContent.indexOf('{{title}}') > -1;
```

**Comment by victorjonsson** [comment]
Quick fix :)

**Comment by chredd** [comment]
Great stuff!

On Thursday, February 19, 2015, Victor Jonsson <notifications@github.com>
wrote:

> Quick fix :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/victorjonsson/Arlima/issues/87#issuecomment-75135865>.
>


-- 
MVH
Christoffer Larsson
@chredd

**Comment by awikell** [comment]
That was quick :)
Thanks!
