### ISSUE TITLE
Preview of an article

### ISSUE THREAD

**Issue by ErikXXon** [victorjonsson/Arlima#88]
I try out the newest beta 27 of Arlima, and you are doing a great job. 
Have one problem, with the preview of articles. See screenshot.

![preview-of-article](https://cloud.githubusercontent.com/assets/6995808/6390643/55502218-bdae-11e4-8b48-f1e0c51e54f9.png)

**Comment by victorjonsson** [comment]
Great catch! I will look into it.

**Comment by victorjonsson** [comment]
Do you get any error in the js-console? What version of Wordpress are you running?

**Comment by ErikXXon** [comment]
I get no errors in js-console, I run Wordpress 4.1.1

**Comment by ErikXXon** [comment]
Find out that if I remove this filter from functions.php the preview work :)

 function my_arlima_tmpl_width( $preview_width, $list ) {
    $preview_width = array(612, 377);
    return $preview_width;
  }
  add_filter('arlima_tmpl_width', 'my_arlima_tmpl_width', 10, 2);

**Comment by victorjonsson** [comment]
Oh, great I will start looking there...

**Comment by victorjonsson** [comment]
I have not ben able to reproduce this error but I found some other 4.1-related issues. Please update to latest version from the master branch and let me know if the problem persists

**Comment by ErikXXon** [comment]
Ill update to the latest and take a look. Thanks

**Comment by victorjonsson** [comment]
If you updated yesterday you must update again today :) ... yesterdays code contained a couple of bugs..

**Comment by ErikXXon** [comment]
Ill update the master and try again, thanks Victor

**Comment by ErikXXon** [comment]
The latest Master update it works fine, as it should and no trouble (WP 4.1.1)
I published an article, but will look around if I find something else. Thanks
