### ISSUE TITLE
Filter arlima_article_content changed?

### ISSUE THREAD

**Issue by EkAndreas** [victorjonsson/Arlima#90]
I just can't find out how the filter arlima_article_content is used and following the documentation fails.

**Comment by victorjonsson** [comment]
Can you please provide me with some code and explain what you're trying to achieve.

**Comment by EkAndreas** [comment]
Very simple content add... It is working in older versions of Arlima.
```
function my_special_content( $data )
{
    $data['content'] .= ' - Testing content add.';
    return $data;
}
add_filter( 'arlima_article_content', 'my_special_content' );
```

**Comment by victorjonsson** [comment]
That's odd... Does the article have any content at all? It will not be rendered if it's considered to be empty (missing title, content, image and child articles)

**Comment by EkAndreas** [comment]
Well there is content but the effect is nothing and the filter is not executed at all :-(
But if I go into TemplateObjectCreator, line 195 and modifies the filter request directly it is ok. Seems like the filter doesn't execute?

**Comment by victorjonsson** [comment]
What changes did you do on line 195?

**Comment by EkAndreas** [comment]
Just for test:
``` 
$obj['html_content'] = 'testing'; //$this->applyFilter('arlima_article_content', $article_counter, $article, $post, $article['content']);

**Comment by EkAndreas** [comment]
Something with the facade?
```
$filtered_data = Arlima_CMSFacade::load()->applyFilters($filter, $data);
```

It seems like WordPress filter isn't executing at all :-(

**Comment by EkAndreas** [comment]
Simple! It was a filter with widget suffix, arlima_template_content-widget.
I'm using lists inside widgets.

**Comment by victorjonsson** [comment]
Maybe it would be good if the inputs in the widget form has some explanations. It's easy to forget about the filter suffix.
