### ISSUE TITLE
Template with two posts side by side

### ISSUE THREAD

**Issue by EkAndreas** [victorjonsson/Arlima#92]
I would like to create a list with two posts side by side in the presentation.
How do I accomplish that with Arlima?

**Comment by victorjonsson** [comment]
You mean like this https://m.youtube.com/watch?feature=youtu.be&v=QHYOIyizQt8 ?

If you don't want the two posts to have a parent you start of with an empty article. Drag the empty article from the meta box labeled "article presets" down to the right in the list manager. Then you drag the two articles, that should be floating beside eachother, as can be seen in the youtube video above.

**Comment by EkAndreas** [comment]
Ahh, ok! I'll try :-)
